### ISSUE TITLE
BlockEntity item capability support

### ISSUE THREAD

**Issue by screret** [Prunoideae/PowerfulJS#2]
would be great to say the least, and save me some headache

**Comment by Prunoideae** [comment]
Block entity support:
https://github.com/Prunoideae/PowerfulJS/blob/13de3c4726d4a024bab699bc2bf644ef57b6b2a5/examples/1.js#L3-L18

Item stack support, if you want to attach capability to existing items, use `ItemEvents.modification` instead:
https://github.com/Prunoideae/PowerfulJS/blob/13de3c4726d4a024bab699bc2bf644ef57b6b2a5/examples/2.js#L3-L20

Use this mod to get documents/completions for current PowerfulJS:
https://www.curseforge.com/minecraft/mc-mods/probejs

Or you can refer to the source to get a list of current capabilities supported:
https://github.com/Prunoideae/PowerfulJS/tree/1.19.2/forge/src/main/java/com/prunoideae/powerfuljs/capabilities/forge/mods

It's unlikely for me to complete documentation for PowerfulJS any time soon (due to continuing development, school assignments, research work etc).

**Comment by Prunoideae** [comment]
Also copied a reply from previous issue since this one is pinned for future problems:

An example to make `apple` wearable but not unequippable on Curio's belt slot:

```js
//startup_scripts
ItemEvents.modification(event => {
	event.modify("apple", modify => {
		modify.attachCapability(
			CuriosCapabilityBuilder.CURIOS.itemStack()
				.canEquip((stack, context) => true)
				.canUnequip((stack, context) => false)
				.modifyAttribute("generic.movement_speed", "apple_speed", 0.1, "multiply_total")
		)
	})
})
```

```js
//server_scripts
ServerEvents.tags('item', event => {
	event.add("curios:belt", "minecraft:apple")
})
```

**Comment by Prunoideae** [comment]
Oh you mean `IItemHandler`, this should be added in next release, it involved complex NBT handling which I wasn't sure at that time, but now it seems doable.
